import React, { useState, useMemo, useCallback } from 'react';
import { useQuery, useAction } from 'convex/react';
import { api } from '../convex/_generated/api';
import { Id, Doc } from '../convex/_generated/dataModel';
import { Icons } from './Icon';
import { useTopicClusters } from '../hooks/useSuggestions';

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

interface TopicMapProps {
  /** Callback when a document is selected */
  onSelectDocument: (documentId: Id<'documents'>) => void;
  /** Callback when a topic is selected for filtering */
  onSelectTopic?: (topic: string) => void;
  /** Workspace ID for workspace-scoped clusters */
  workspaceId?: Id<'workspaces'>;
  /** Additional CSS classes */
  className?: string;
  /** View mode: bubble (default) or tree */
  viewMode?: 'bubble' | 'tree' | 'list';
}

interface TopicCluster {
  _id: Id<'topicClusters'>;
  name: string;
  description?: string;
  documentIds: Id<'documents'>[];
  primaryTags: string[];
  documentCount: number;
  averageRelevance: number;
  isAutoGenerated: boolean;
}

// ═══════════════════════════════════════════════════════════════
// Bubble View Component
// ═══════════════════════════════════════════════════════════════

interface BubbleProps {
  cluster: TopicCluster;
  onClick: () => void;
  isSelected: boolean;
  maxCount: number;
}

const Bubble: React.FC<BubbleProps> = ({ cluster, onClick, isSelected, maxCount }) => {
  // Calculate bubble size based on document count
  const minSize = 60;
  const maxSize = 120;
  const size = minSize + ((cluster.documentCount / maxCount) * (maxSize - minSize));

  // Generate a consistent color based on cluster name
  const hashCode = (str: string) => {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return hash;
  };

  const hue = Math.abs(hashCode(cluster.name)) % 360;
  const backgroundColor = `hsla(${hue}, 70%, 60%, 0.2)`;
  const borderColor = `hsla(${hue}, 70%, 50%, ${isSelected ? 1 : 0.5})`;
  const textColor = `hsl(${hue}, 70%, 40%)`;

  return (
    <button
      onClick={onClick}
      className={`
        relative rounded-full flex flex-col items-center justify-center
        transition-all duration-200 hover:scale-105 hover:shadow-lg
        ${isSelected ? 'ring-2 ring-offset-2 ring-primary' : ''}
      `}
      style={{
        width: size,
        height: size,
        backgroundColor,
        borderWidth: 2,
        borderColor,
      }}
    >
      <span
        className="font-semibold text-xs text-center px-2 line-clamp-2"
        style={{ color: textColor }}
      >
        {cluster.name}
      </span>
      <span className="text-[10px] mt-0.5 opacity-70" style={{ color: textColor }}>
        {cluster.documentCount} doc{cluster.documentCount !== 1 ? 's' : ''}
      </span>
    </button>
  );
};

// ═══════════════════════════════════════════════════════════════
// Tree View Component
// ═══════════════════════════════════════════════════════════════

interface TreeNodeProps {
  cluster: TopicCluster;
  onSelectCluster: (cluster: TopicCluster) => void;
  onSelectDocument: (documentId: Id<'documents'>) => void;
  isExpanded: boolean;
  onToggle: () => void;
  documents: Array<{ _id: Id<'documents'>; topic: string }>;
}

const TreeNode: React.FC<TreeNodeProps> = ({
  cluster,
  onSelectCluster,
  onSelectDocument,
  isExpanded,
  onToggle,
  documents,
}) => {
  return (
    <div className="select-none">
      {/* Cluster node */}
      <div className="flex items-center gap-2 py-1.5">
        <button
          onClick={onToggle}
          className="p-0.5 rounded hover:bg-surface-hover text-secondary"
        >
          {isExpanded ? (
            <Icons.ChevronDown className="w-4 h-4" />
          ) : (
            <Icons.ChevronRight className="w-4 h-4" />
          )}
        </button>
        <button
          onClick={() => onSelectCluster(cluster)}
          className="flex items-center gap-2 flex-1 text-left hover:text-primary transition-colors"
        >
          <Icons.Folder className="w-4 h-4 text-amber-500" />
          <span className="font-medium text-sm text-main">{cluster.name}</span>
          <span className="text-xs text-secondary">({cluster.documentCount})</span>
        </button>
      </div>

      {/* Document nodes */}
      {isExpanded && (
        <div className="ml-6 border-l border-border pl-2 space-y-0.5">
          {documents.map((doc) => (
            <button
              key={doc._id}
              onClick={() => onSelectDocument(doc._id)}
              className="flex items-center gap-2 py-1 px-2 w-full text-left rounded hover:bg-surface-hover transition-colors group"
            >
              <Icons.FileText className="w-3.5 h-3.5 text-secondary group-hover:text-primary" />
              <span className="text-sm text-secondary group-hover:text-main truncate">
                {doc.topic}
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// List View Component
// ═══════════════════════════════════════════════════════════════

interface ListItemProps {
  cluster: TopicCluster;
  onClick: () => void;
  isSelected: boolean;
}

const ListItem: React.FC<ListItemProps> = ({ cluster, onClick, isSelected }) => {
  return (
    <button
      onClick={onClick}
      className={`
        w-full flex items-center gap-3 p-3 rounded-lg text-left transition-colors
        ${isSelected
          ? 'bg-primary/10 border-primary'
          : 'bg-surface hover:bg-surface-hover border-border'
        }
        border
      `}
    >
      <div className={`
        w-10 h-10 rounded-lg flex items-center justify-center text-lg font-bold
        ${isSelected ? 'bg-primary text-white' : 'bg-surface-hover text-main'}
      `}>
        {cluster.documentCount}
      </div>
      <div className="flex-1 min-w-0">
        <h4 className={`font-medium text-sm ${isSelected ? 'text-primary' : 'text-main'}`}>
          {cluster.name}
        </h4>
        {cluster.primaryTags.length > 0 && (
          <div className="flex flex-wrap gap-1 mt-1">
            {cluster.primaryTags.slice(0, 3).map((tag) => (
              <span
                key={tag}
                className="px-1.5 py-0.5 text-[10px] bg-surface-hover text-secondary rounded"
              >
                {tag}
              </span>
            ))}
          </div>
        )}
      </div>
      <Icons.ChevronRight className={`w-4 h-4 ${isSelected ? 'text-primary' : 'text-secondary'}`} />
    </button>
  );
};

// ═══════════════════════════════════════════════════════════════
// Main Component
// ═══════════════════════════════════════════════════════════════

const TopicMap: React.FC<TopicMapProps> = ({
  onSelectDocument,
  onSelectTopic,
  workspaceId,
  className = '',
  viewMode: initialViewMode = 'bubble',
}) => {
  const [viewMode, setViewMode] = useState(initialViewMode);
  const [selectedCluster, setSelectedCluster] = useState<TopicCluster | null>(null);
  const [expandedClusters, setExpandedClusters] = useState<Set<string>>(new Set());
  const [isGenerating, setIsGenerating] = useState(false);

  // Fetch clusters
  const { clusters, isLoading, regenerate } = useTopicClusters(workspaceId);

  // Get documents for selected cluster
  const clusterDocuments = useQuery(
    api.documents.list,
    selectedCluster ? { projectId: undefined } : 'skip'
  );

  // Filter documents belonging to selected cluster
  const selectedClusterDocs = useMemo(() => {
    if (!selectedCluster || !clusterDocuments) return [];

    return clusterDocuments
      .filter((doc) => selectedCluster.documentIds.includes(doc._id))
      .map((doc) => ({ _id: doc._id, topic: doc.topic }));
  }, [selectedCluster, clusterDocuments]);

  // Get documents for tree view
  const allDocuments = useQuery(api.documents.list, { projectId: undefined });

  const getDocumentsForCluster = useCallback((cluster: TopicCluster) => {
    if (!allDocuments) return [];
    return allDocuments
      .filter((doc) => cluster.documentIds.includes(doc._id))
      .map((doc) => ({ _id: doc._id, topic: doc.topic }));
  }, [allDocuments]);

  // Calculate max count for bubble sizing
  const maxCount = useMemo(() => {
    return Math.max(...clusters.map((c) => c.documentCount), 1);
  }, [clusters]);

  // Toggle cluster expansion in tree view
  const toggleCluster = useCallback((clusterId: string) => {
    setExpandedClusters((prev) => {
      const next = new Set(prev);
      if (next.has(clusterId)) {
        next.delete(clusterId);
      } else {
        next.add(clusterId);
      }
      return next;
    });
  }, []);

  // Handle cluster selection
  const handleSelectCluster = useCallback((cluster: TopicCluster) => {
    setSelectedCluster((prev) => prev?._id === cluster._id ? null : cluster);
    onSelectTopic?.(cluster.name);
  }, [onSelectTopic]);

  // Handle regenerate clusters
  const handleRegenerate = async () => {
    setIsGenerating(true);
    try {
      await regenerate();
    } catch (err) {
      console.error('Failed to regenerate clusters:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  if (isLoading) {
    return (
      <div className={`bg-surface border border-border rounded-xl p-6 ${className}`}>
        <div className="flex items-center justify-center">
          <div className="flex items-center gap-2 text-sm text-secondary">
            <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
            Loading topic map...
          </div>
        </div>
      </div>
    );
  }

  if (clusters.length === 0) {
    return (
      <div className={`bg-surface border border-border rounded-xl p-6 ${className}`}>
        <div className="flex flex-col items-center justify-center text-center">
          <Icons.Map className="w-12 h-12 text-secondary/30 mb-3" />
          <h3 className="font-medium text-main mb-1">No Topic Clusters Yet</h3>
          <p className="text-sm text-secondary mb-4">
            Generate topic clusters to organize your documents by theme
          </p>
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Icons.Sparkles className="w-4 h-4" />
                Generate Clusters
              </>
            )}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-surface border border-border rounded-xl overflow-hidden ${className}`}>
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-surface-hover/30">
        <div className="flex items-center gap-2">
          <Icons.Map className="w-5 h-5 text-purple-500" />
          <h3 className="font-semibold text-sm text-main">Topic Map</h3>
          <span className="text-xs text-secondary">({clusters.length} topics)</span>
        </div>

        <div className="flex items-center gap-2">
          {/* View mode toggle */}
          <div className="flex items-center bg-background rounded-lg p-0.5">
            {[
              { mode: 'bubble' as const, icon: Icons.Grid3x3, label: 'Bubbles' },
              { mode: 'tree' as const, icon: Icons.FolderTree, label: 'Tree' },
              { mode: 'list' as const, icon: Icons.List, label: 'List' },
            ].map(({ mode, icon: Icon, label }) => (
              <button
                key={mode}
                onClick={() => setViewMode(mode)}
                className={`p-1.5 rounded transition-colors ${
                  viewMode === mode
                    ? 'bg-surface text-primary'
                    : 'text-secondary hover:text-main'
                }`}
                title={label}
              >
                <Icon className="w-4 h-4" />
              </button>
            ))}
          </div>

          {/* Regenerate button */}
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="p-1.5 rounded hover:bg-background text-secondary hover:text-main transition-colors disabled:opacity-50"
            title="Regenerate clusters"
          >
            <Icons.Refresh className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-4">
        {/* Bubble View */}
        {viewMode === 'bubble' && (
          <div className="flex flex-wrap gap-3 justify-center min-h-[200px] items-center">
            {clusters.map((cluster) => (
              <Bubble
                key={cluster._id}
                cluster={cluster}
                onClick={() => handleSelectCluster(cluster)}
                isSelected={selectedCluster?._id === cluster._id}
                maxCount={maxCount}
              />
            ))}
          </div>
        )}

        {/* Tree View */}
        {viewMode === 'tree' && (
          <div className="space-y-1">
            {clusters.map((cluster) => (
              <TreeNode
                key={cluster._id}
                cluster={cluster}
                onSelectCluster={handleSelectCluster}
                onSelectDocument={onSelectDocument}
                isExpanded={expandedClusters.has(cluster._id)}
                onToggle={() => toggleCluster(cluster._id)}
                documents={getDocumentsForCluster(cluster)}
              />
            ))}
          </div>
        )}

        {/* List View */}
        {viewMode === 'list' && (
          <div className="space-y-2">
            {clusters.map((cluster) => (
              <ListItem
                key={cluster._id}
                cluster={cluster}
                onClick={() => handleSelectCluster(cluster)}
                isSelected={selectedCluster?._id === cluster._id}
              />
            ))}
          </div>
        )}

        {/* Selected cluster documents */}
        {selectedCluster && viewMode !== 'tree' && (
          <div className="mt-4 pt-4 border-t border-border">
            <div className="flex items-center justify-between mb-3">
              <h4 className="font-medium text-sm text-main">
                Documents in "{selectedCluster.name}"
              </h4>
              <button
                onClick={() => setSelectedCluster(null)}
                className="p-1 rounded hover:bg-surface-hover text-secondary hover:text-main transition-colors"
              >
                <Icons.X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-1 max-h-48 overflow-y-auto">
              {selectedClusterDocs.map((doc) => (
                <button
                  key={doc._id}
                  onClick={() => onSelectDocument(doc._id)}
                  className="flex items-center gap-2 w-full p-2 rounded-lg text-left hover:bg-surface-hover transition-colors group"
                >
                  <Icons.FileText className="w-4 h-4 text-secondary group-hover:text-primary" />
                  <span className="text-sm text-main group-hover:text-primary truncate">
                    {doc.topic}
                  </span>
                </button>
              ))}

              {selectedClusterDocs.length === 0 && (
                <p className="text-sm text-secondary text-center py-4">
                  Loading documents...
                </p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default TopicMap;
